### ISSUE TITLE
Is it possible to install custom firmware on the IKBC C87?

### ISSUE THREAD

**Issue by lowercasename** [pok3r-custom/pok3r_re_firmware#28]
And if it isn't possible, is it in the pipeline - or is the processor on the C87 not up to scratch? Thank you!

**Comment by ChaoticConundrum** [comment]
Looking at some pictures of the C87, it looks like they use a "VISION" processor I've seen before, but never managed to find documentation on. It's most likely an application-specific chip for keyboards, and not programmable.

If you can find more information, I'll look into it, but I have no plans to work on any keyboards with this processor.

**Comment by lowercasename** [comment]
Understood, thanks for the quick reply! If I ever get around to contacting IKBC maybe I'll find out more.
